### ISSUE TITLE
Navbar implementation

### ISSUE THREAD

**Issue by arsovskidario** [arsovskidario/project-honey#2]
Navbar functionality:
- Should stick to top of screen and scroll with page
- Should toggle between MK/ENG
- 
Will have the following design

![image](https://github.com/arsovskidario/project-honey/assets/29378234/fbcadb60-8491-46f0-beaf-9c0ee6a6784c)

**Comment by arsovskidario** [comment]
# TODO
- [x] Add user and shopping cart navbar section
- [X] Fix height of navbar so it doesnt take whole page
- [X] Clean up tailwind css
- [X] Converts ahref to Links
- [ ] **FEATURE:** Logo to svg and text to normal text with same font 
- [ ] Should stick to top of screen and scroll with page
- [X] Shrink functionality should open search bar and sections bar for mobile
